apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: build artifact
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build-deploy-artifact:
    steps:
      - name: Build Artifact
        run: |
          echo "hello world"
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
      - name: Publish build artifact
        kind: build
        uses: cloudbees-io/register-build-artifact@v1
        with:
          version: 1.0.0
          url: docker.io/artifact/cbp:1.0.0
          digest: sha256:10a123ee08af5e43a7fea6c4cf9c25ccf269ee113168c19722f87876677c5cb2
          name: test-artifact-ninja
